version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 99
  assignees:
  - adriangodong
  ignore:
  - dependency-name: MSTest.TestFramework
    versions:
    - 2.1.2
    - 2.2.1
    - 2.2.2
  - dependency-name: MSTest.TestAdapter
    versions:
    - 2.1.2
    - 2.2.1
    - 2.2.2
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.8.3
    - 16.9.1
  - dependency-name: Moq
    versions:
    - 4.16.0
  - dependency-name: Amazon.Lambda.Core
    versions:
    - 1.2.0
  rebase-strategy: disabled
