image: Visual Studio 2019
configuration: Release
version: '{build}'

dotnet_csproj:
  patch: true
  file: 'AlexaLambdaHandler\AlexaLambdaHandler.csproj'
  version: $(appveyor_repo_tag_name)

before_build:
- cmd: dotnet restore

build:
  project: AlexaLambdaHandler.sln
  verbosity: normal

test_script:
- cmd: >-
    dotnet test AlexaLambdaHandler.Tests

artifacts:
- path: '**/*.nupkg'
  name: Nuget Packages

deploy:
- provider: NuGet
  api_key:
    secure: 4WizYTuSBPn9NYDry8Wr+xhszXDKo12ogInULGGAXwKAXmmlaVMapSpjkQEJF0nJ
  on:
    appveyor_repo_tag: true
